const API_BASE = 'https://voice-rag-goa-visora.onrender.com';

// --------------------------------------------------
// Generic helper
// --------------------------------------------------
async function handleResponse(response, defaultMessage) {
  if (!response.ok) {
    let message = defaultMessage;

    try {
      const data = await response.json();

      if (data?.detail) {
        message =
          typeof data.detail === 'string'
            ? data.detail
            : JSON.stringify(data.detail);
      }
    } catch {
      // Ignore JSON parsing error
    }

    throw new Error(
      `${message} (HTTP ${response.status})`
    );
  }

  return response.json();
}

// --------------------------------------------------
// Health
// --------------------------------------------------
export async function fetchHealth() {
  const response = await fetch(
    `${API_BASE}/health`,
    {
      method: 'GET',
      headers: {
        Accept: 'application/json'
      }
    }
  );

  return handleResponse(
    response,
    'Backend health check failed'
  );
}

// --------------------------------------------------
// Config
// --------------------------------------------------
export async function fetchConfig() {
  const response = await fetch(
    `${API_BASE}/api/config`,
    {
      method: 'GET',
      headers: {
        Accept: 'application/json'
      }
    }
  );

  return handleResponse(
    response,
    'Failed to fetch backend configuration'
  );
}

// --------------------------------------------------
// TEXT RAG
// --------------------------------------------------
export async function sendTextQuery(queryText) {
  if (!queryText || !queryText.trim()) {
    throw new Error('Please enter a query.');
  }

  console.log(
    '[API] Sending text query:',
    queryText
  );

  const response = await fetch(
    `${API_BASE}/api/rag`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json'
      },
      body: JSON.stringify({
        query: queryText.trim()
      })
    }
  );

  const data = await handleResponse(
    response,
    'RAG query failed'
  );

  console.log(
    '[API] Text RAG response:',
    data
  );

  return data;
}

// --------------------------------------------------
// VOICE RAG
// --------------------------------------------------
export async function sendVoiceQuery(audioFile) {
  if (!audioFile) {
    throw new Error('No audio recording received.');
  }

  console.log(
    '[API] Preparing voice upload:',
    {
      name: audioFile.name,
      type: audioFile.type,
      size: audioFile.size
    }
  );

  if (audioFile.size === 0) {
    throw new Error('The recorded audio file is empty.');
  }

  const formData = new FormData();

  // IMPORTANT:
  // Use the REAL filename generated by MediaRecorder.
  // Do NOT rename WebM/M4A/OGG to recording.wav.
  formData.append(
    'file',
    audioFile,
    audioFile.name || 'recording.webm'
  );

  console.log(
    '[API] Uploading to:',
    `${API_BASE}/api/voice-rag`
  );

  const response = await fetch(
    `${API_BASE}/api/voice-rag`,
    {
      method: 'POST',
      body: formData
    }
  );

  const data = await handleResponse(
    response,
    'Voice RAG request failed'
  );

  console.log(
    '[API] Voice RAG response:',
    data
  );

  return data;
}

// --------------------------------------------------
// STT ONLY
// --------------------------------------------------
export async function sendSTTOnly(audioFile) {
  if (!audioFile) {
    throw new Error('No audio file received.');
  }

  const formData = new FormData();

  formData.append(
    'file',
    audioFile,
    audioFile.name || 'recording.webm'
  );

  console.log(
    '[API] Sending audio to STT:',
    {
      name: audioFile.name,
      type: audioFile.type,
      size: audioFile.size
    }
  );

  const response = await fetch(
    `${API_BASE}/api/stt`,
    {
      method: 'POST',
      body: formData
    }
  );

  const data = await handleResponse(
    response,
    'Speech-To-Text request failed'
  );

  console.log(
    '[API] STT response:',
    data
  );

  return data;
}
