from app.models.data_models import GuardrailResult

class OutputValidationGuardrail:
    """Ensures output format compliance, non-emptiness, and status field integrity."""
    def validate(self, answer: str) -> GuardrailResult:
        if not answer or not answer.strip():
            return GuardrailResult(
                passed=False,
                reason="Empty output generated by LLM provider",
                refusal_message="I encountered an internal error formatting the response. Please try again."
            )
        return GuardrailResult(passed=True)
